version: "3.9"
services:
  website:
    restart: always
    image: image.ae30.at
    container_name: container.ae30.at
    build: .
    ports:
      - "8091:8080"
    environment:
      - BASE_URL=/ae30
      - HOST=0.0.0.0
      - NODE_OPTIONS=--max_old_space_size=4096
  # https://github.com/vencax/netlify-cms-github-oauth-provider/
  oauth:
    restart: always
    image: image.ae30.auth
    container_name: container.ae30.auth
    build:
      context: ./github-oauth/
    ports:
      - "8092:6000"
